apiVersion: v1
kind: Service
metadata:
  name: converter-service
  namespace: cool-prod
spec:
  selector:
    app: converter-service
  ports:
    - protocol: TCP
      port: 6789
      targetPort: 6789
      name: http
